### ISSUE TITLE
Bug in student when initializing

### ISSUE THREAD

**Issue by kungbob** [kungbob/code_nova#1]
Initialization problem found. Bugs in models.py of student folder

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0000016EAE9F
7048>
Traceback (most recent call last):

  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\aut
oreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\mana
gement\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\aut
oreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\mana
gement\__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\aut
oreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\site-packages\django\__init__.
py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\site-packages\django\apps\regi
stry.py", line 112, in populate
    app_config.import_models()
  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\site-packages\django\apps\conf
ig.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "F:\Users\kungbob\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 1
26, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\Users\kungbob\OneDrive\code\python\AI\code_nova\student\models.py", line 10, in <module
>
    class Student(models.Model):
  File "F:\Users\kungbob\OneDrive\code\python\AI\code_nova\student\models.py", line 11, in Student

    user = models.OneToOneField(User)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by kungbob** [comment]
Bugs found not only in Student, multiple bugs are found also.
Fixed in latest commit 7f3984d3197e67ed95be5ccfe50030bc019f5c60.
